server:
  port: 81

spring:
  application:
    name: cloud-order-hystrix
feign.client.config.default.connect-timeout: 5000
feign.client.config.default.read-timeout: 30000
feign:
  httpclient:
    enabled: true
    connection-timeout: 2000
    max-connections: 500
    max-connections-per-route: 50
    connection-timer-repeat: 2000
    time-to-live: 5
    time-to-live-unit: minutes
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: hystrixorder81
    #访问路径显示ip
    prefer-ip-address: true