server:
  port: 81

spring:
  application:
    name: cloud-order-service
    #注册zookeeper
  #cloud:
  #  zookeeper:
  
  #    connect-string: localhost:2181
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
